Startup pack
bernatmv/thegame pull request #26
Opened 2017-05-14 21:50 UTC by watarhu

Added items (full profile)

2017-05-17 08:48 UTC, bernatmv requested changes

2017-05-17 08:48 UTC, bernatmv commented on assets/items/chicken_001.json
> +    "alive": true,
ok

2017-05-17 08:48 UTC, bernatmv commented on assets/items/chicken_001.json
> +    "chatters": [
no té massa sentit, chatter ja inlou una pluralitat implícita, chatters no té un ús

2017-05-17 08:48 UTC, bernatmv commented on docs/api/dtos/itemDto.md
> +    chatters: Array<string>;
same

2017-06-18 23:06 UTC, watarhu commented
en principi els canvis estan fets, i ja es poden veure els enemics.

2017-06-19 14:28 UTC, bernatmv approved these changes

2017-06-19 14:28 UTC, merged